# Generated by Django 4.0.4 on 2022-05-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('person_age', models.IntegerField(default=0)),
                ('person_income', models.IntegerField(default=0)),
                ('person_home_ownership', models.CharField(choices=[('RENT', 'RENT'), ('OWN', 'OWN'), ('MORTGAGE', 'MORTGAGE'), ('OTHER', 'OTHER')], max_length=15)),
                ('person_emp_length', models.IntegerField(default=0)),
                ('loan_intent', models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('EDUCATION', 'EDUCATION'), ('MEDICAL', 'MEDICAL'), ('VENTURE', 'VENTURE'), ('HOMEIMPROVEMENT', 'HOME IMPROVEMENT'), ('DEBTCONSOLIDATION', 'DEBT CONSOLIDATION')], max_length=25)),
                ('loan_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=15)),
                ('loan_amnt', models.IntegerField(default=0)),
                ('loan_int_rate', models.FloatField(default=0.0)),
                ('loan_percent_income', models.FloatField(default=0.0)),
                ('cb_person_default_on_file', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=15)),
                ('cb_person_cred_hist_length', models.IntegerField()),
            ],
        ),
    ]
